version: '3.9'

services:
  duckdb:
    build:
      context: .
      dockerfile: Dockerfile.duckdb
    volumes:
      - .:/app
    working_dir: /app
    command: python dbserve.py
    ports:
      - "9999:9999"
  ml:
    build: ./model
    ports:
      - "5000:5000"
    
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    volumes:
      - .:/app
    working_dir: /app
    command: python front.py
    ports:
      - "5801:8501"
    depends_on:
      - duckdb
      - ml
